/* This file is automatically generated by pict_opcode.py. */

enum {
kOp_NOP,
kOp_Clip,
kOp_BkPat,
kOp_TxFont,
kOp_TxFace,
kOp_TxMode,
kOp_SpExtra,
kOp_PnSize,
kOp_PnMode,
kOp_PnPat,
kOp_FillPat,
kOp_OvSize,
kOp_Origin,
kOp_TxSize,
kOp_FgColor,
kOp_BkColor,
kOp_TxRatio,
kOp_VersionOp,
kOp_BkPixPat,
kOp_PnPixPat,
kOp_FillPixPat,
kOp_PnLocHFrac,
kOp_ChExtra,
kOp_RGBFgCol = 0x001a,
kOp_RGBBkCol,
kOp_HiliteMode,
kOp_HiliteColor,
kOp_DefHilite,
kOp_OpColor,
kOp_Line,
kOp_LineFrom,
kOp_ShortLine,
kOp_ShortLineFrom,
kOp_LongText = 0x0028,
kOp_DHText,
kOp_DVText,
kOp_DHDVText,
kOp_fontName,
kOp_lineJustify,
kOp_glyphState,
kOp_frameRect = 0x0030,
kOp_paintRect,
kOp_eraseRect,
kOp_invertRect,
kOp_fillRect,
kOp_frameSameRect = 0x0038,
kOp_paintSameRect,
kOp_eraseSameRect,
kOp_invertSameRect,
kOp_fillSameRect,
kOp_frameRRect = 0x0040,
kOp_paintRRect,
kOp_eraseRRect,
kOp_invertRRect,
kOp_fillRRect,
kOp_frameSameRRect = 0x0048,
kOp_paintSameRRect,
kOp_eraseSameRRect,
kOp_invertSameRRect,
kOp_fillSameRRect,
kOp_frameOval = 0x0050,
kOp_paintOval,
kOp_eraseOval,
kOp_invertOval,
kOp_fillOval,
kOp_frameSameOval = 0x0058,
kOp_paintSameOval,
kOp_eraseSameOval,
kOp_invertSameOval,
kOp_fillSameOval,
kOp_frameArc = 0x0060,
kOp_paintArc,
kOp_eraseArc,
kOp_invertArc,
kOp_fillArc,
kOp_frameSameArc = 0x0068,
kOp_paintSameArc,
kOp_eraseSameArc,
kOp_invertSameArc,
kOp_fillSameArc,
kOp_framePoly = 0x0070,
kOp_paintPoly,
kOp_erasePoly,
kOp_invertPoly,
kOp_fillPoly,
kOp_frameSamePoly = 0x0078,
kOp_paintSamePoly,
kOp_eraseSamePoly,
kOp_invertSamePoly,
kOp_fillSamePoly,
kOp_frameRgn = 0x0080,
kOp_paintRgn,
kOp_eraseRgn,
kOp_invertRgn,
kOp_fillRgn,
kOp_frameSameRgn = 0x0088,
kOp_paintSameRgn,
kOp_eraseSameRgn,
kOp_invertSameRgn,
kOp_fillSameRgn,
kOp_BitsRect = 0x0090,
kOp_BitsRgn,
kOp_PackBitsRect = 0x0098,
kOp_PackBitsRgn,
kOp_DirectBitsRect,
kOp_DirectBitsRgn,
kOp_ShortComment = 0x00a0,
kOp_LongComment,
kOp_OpEndPic = 0x00ff,
kOp_HeaderOp = 0x0c00,
kOp_CompressedQuickTime = 0x8200,
kOp_UncompressedQuickTime
};

static const char kOpcodeNames[] =
"NOP\0"
"Clip\0"
"BkPat\0"
"TxFont\0"
"TxFace\0"
"TxMode\0"
"SpExtra\0"
"PnSize\0"
"PnMode\0"
"PnPat\0"
"FillPat\0"
"OvSize\0"
"Origin\0"
"TxSize\0"
"FgColor\0"
"BkColor\0"
"TxRatio\0"
"VersionOp\0"
"BkPixPat\0"
"PnPixPat\0"
"FillPixPat\0"
"PnLocHFrac\0"
"ChExtra\0"
"RGBFgCol\0"
"RGBBkCol\0"
"HiliteMode\0"
"HiliteColor\0"
"DefHilite\0"
"OpColor\0"
"Line\0"
"LineFrom\0"
"ShortLine\0"
"ShortLineFrom\0"
"LongText\0"
"DHText\0"
"DVText\0"
"DHDVText\0"
"fontName\0"
"lineJustify\0"
"glyphState\0"
"frameRect\0"
"paintRect\0"
"eraseRect\0"
"invertRect\0"
"fillRect\0"
"frameSameRect\0"
"paintSameRect\0"
"eraseSameRect\0"
"invertSameRect\0"
"fillSameRect\0"
"frameRRect\0"
"paintRRect\0"
"eraseRRect\0"
"invertRRect\0"
"fillRRect\0"
"frameSameRRect\0"
"paintSameRRect\0"
"eraseSameRRect\0"
"invertSameRRect\0"
"fillSameRRect\0"
"frameOval\0"
"paintOval\0"
"eraseOval\0"
"invertOval\0"
"fillOval\0"
"frameSameOval\0"
"paintSameOval\0"
"eraseSameOval\0"
"invertSameOval\0"
"fillSameOval\0"
"frameArc\0"
"paintArc\0"
"eraseArc\0"
"invertArc\0"
"fillArc\0"
"frameSameArc\0"
"paintSameArc\0"
"eraseSameArc\0"
"invertSameArc\0"
"fillSameArc\0"
"framePoly\0"
"paintPoly\0"
"erasePoly\0"
"invertPoly\0"
"fillPoly\0"
"frameSamePoly\0"
"paintSamePoly\0"
"eraseSamePoly\0"
"invertSamePoly\0"
"fillSamePoly\0"
"frameRgn\0"
"paintRgn\0"
"eraseRgn\0"
"invertRgn\0"
"fillRgn\0"
"frameSameRgn\0"
"paintSameRgn\0"
"eraseSameRgn\0"
"invertSameRgn\0"
"fillSameRgn\0"
"BitsRect\0"
"BitsRgn\0"
"PackBitsRect\0"
"PackBitsRgn\0"
"DirectBitsRect\0"
"DirectBitsRgn\0"
"ShortComment\0"
"LongComment\0"
"OpEndPic\0"
"HeaderOp\0"
"CompressedQuickTime\0"
"UncompressedQuickTime";

static const unsigned short kOpcodeNameTable[256] = {
1,5,10,16,23,30,37,45,52,59,65,73,80,87,94,102,
110,118,128,137,146,157,168,0,0,0,176,185,194,205,217,227,
235,240,249,259,0,0,0,0,273,282,289,296,305,314,326,0,
337,347,357,367,378,0,0,0,387,401,415,429,444,0,0,0,
457,468,479,490,502,0,0,0,512,527,542,557,573,0,0,0,
587,597,607,617,628,0,0,0,637,651,665,679,694,0,0,0,
707,716,725,734,744,0,0,0,752,765,778,791,805,0,0,0,
817,827,837,847,858,0,0,0,867,881,895,909,924,0,0,0,
937,946,955,964,974,0,0,0,982,995,1008,1021,1035,0,0,0,
1047,1056,0,0,0,0,0,0,1064,1077,1089,1104,0,0,0,0,
1118,1131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1143
};

static const short kOpcodeDataTable[256] = {
0,-kTypeRegion-1,8,2,
1,2,4,4,
2,8,8,4,
4,2,4,4,
8,-kTypeVersion-1,-kTypePattern-1,-kTypePattern-1,
-kTypePattern-1,2,2,-kTypeNotDetermined-1,
-kTypeNotDetermined-1,-kTypeNotDetermined-1,6,6,
0,6,0,6,
8,4,6,2,
-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,
-kTypeText-1,-kTypeText-1,-kTypeText-1,-kTypeText-1,
-kTypeText-1,10,8,-kTypeData16-1,
8,8,8,8,
8,8,8,8,
0,0,0,0,
0,0,0,0,
8,8,8,8,
8,8,8,8,
0,0,0,0,
0,0,0,0,
8,8,8,8,
8,8,8,8,
0,0,0,0,
0,0,0,0,
12,12,12,12,
12,12,12,12,
4,4,4,4,
4,4,4,4,
-kTypePolygon-1,-kTypePolygon-1,-kTypePolygon-1,-kTypePolygon-1,
-kTypePolygon-1,-kTypePolygon-1,-kTypePolygon-1,-kTypePolygon-1,
0,0,0,0,
0,0,0,0,
-kTypeRegion-1,-kTypeRegion-1,-kTypeRegion-1,-kTypeRegion-1,
-kTypeRegion-1,-kTypeRegion-1,-kTypeRegion-1,-kTypeRegion-1,
0,0,0,0,
0,0,0,0,
-kTypePixelData-1,-kTypePixelData-1,-kTypeData16-1,-kTypeData16-1,
-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,
-kTypePixelData-1,-kTypePixelData-1,-kTypePixelData-1,-kTypePixelData-1,
-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,
2,-kTypeLongComment-1,-kTypeData16-1,-kTypeData16-1,
-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,
-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,
-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,-kTypeData16-1,
0,0,0,0,
0,0,0,0,
0,0,0,0,
0,0,0,0,
0,0,0,0,
0,0,0,0,
0,0,0,0,
0,0,0,0,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,
-kTypeData32-1,-kTypeData32-1,-kTypeData32-1,-kTypeEnd-1
};

static const struct extended_opcode kExtendedOpcodes[] = {
{0x0c00, 1152},
{0x8200, 1161},
{0x8201, 1181}
};
